name: Crisol de Cuerda
nameShort: Crisol

startDate: 2026-07-26
endDate: 2026-08-02
dateTimezone: Europe/Madrid

registration:
  coursePrice: 750
  bookingFee: 75
  refundLimit: 80 # percentage
  endOfEarlyRegistrationDate: 2026-05-01
  underageAuthorisationFile: /docs/over-14-authorisation.pdf
  under14AuthorisationFile: /docs/under-14-authorisation.pdf
  acceptanceOfGuardianshipFile: /docs/under-14-acceptance-of-guardianship.pdf
  scholarshipDiscount: 25 # percentage
  familyDiscount: 10 # percentage
  familyDiscountMinimum: 3
  scholarshipLimitDate: 2026-05-15
  referralDiscount: 10 # percentage

displayRegistrationSlogan: true
displayRegistrationCTA: false
registrationLink: https://inscripciones.crisoldecuerda.com
hideRegistrationPage: true

pendingTeachers: true

newsletterLink: https://eepurl.com/ggOBLr
socialMedia:
  facebook: https://www.facebook.com/CrisoldeCuerda
  instagram: https://www.instagram.com/crisoldecuerda
  patreon: https://www.patreon.com/crisoldecuerda
  spotify: https://open.spotify.com/embed/playlist/4LmL2DW8S5N0D0W1TgDHEf?utm_source=generator&theme=0
  tiktok: https://www.tiktok.com/@crisoldecuerda
  vimeo: http://vimeo.com/user18504489
  youtube: https://www.youtube.com/user/CrisolDeCuerda
