registrationSlogan:
  en: Registration will open on March 29th!
  es: ¡Abrimos inscripciones el 29 de marzo!
registrationCta:
  en: Register now
  es: Regístrate

aboutLinks:
  - title:
      en: The Spirit of Crisol
      es: El Espíritu Crisol
    subtitle:
      en: Why are we here?
      es: ¿Por qué estamos aquí?
    img: https://www.crisoldecuerda.com/assets/images/index/crisol_spirit.webp
    link: /about
  - title:
      en: The Lessons
      es: Las Clases
    subtitle:
      en: How do they work and what is special about them?
      es: ¿Cómo funcionan y qué tienen de especial?
    img: https://www.crisoldecuerda.com/assets/images/index/classes.webp
    link: /about/classes
  - title:
      en: A bit of History
      es: Un Poco de Historia
    subtitle:
      en: How it all started
      es: ¿Cómo empezó todo?
    img: https://www.crisoldecuerda.com/assets/images/index/history.webp
    link: /about/history

infoSection:
  information:
    title:
      en: Important information
      es: Información importante
    subtitle:
      en: Everything you need to know about Crisol de Cuerda. And some advice as well!
      es: Todo lo que necesitas saber acerca de Crisol de Cuerda. ¡Todos nuestros consejos!
    link: /about
  prices:
    title:
      en: Prices
      es: Precios
    subtitle:
      en: Here's the information about our prices. Limited availability, don't miss your spot!
      es: Infórmate acerca de los precios. ¡Plazas limitadas, no te lo pierdas!
    link: /registration
  register:
    title:
      en: How to register
      es: Cómo inscribirse
    subtitle:
      en: The registration form has been simplified to make it as easy as possible!
      es: Hemos mejorado nuestro formulario para que inscribirse resulte de lo más sencillo
    link: /registration
  scholarships:
    title:
      en: Scholarships
      es: Becas
    subtitle:
      en: There's a scholarship program at your disposal to help those who need it most
      es: Como cada año, ponemos a vuestra disposición nuestro programa de becas
    link: /registration

knowMoreButton:
  en: Know more
  es: Saber más

pendingTeachers:
  en: More teachers to confirm. Visit us soon!
  es: Más profesores a confirmar. ¡Visítanos pronto!
