bg: media.webp
title:
  en: Media
  es: Media
mediaCaptcha:
  en: Wanna see what Crisol looks like? Here's what we did in our past editions.
  es: ¿Quieres ver lo que pasa en Crisol? Esto es lo que hicimos en las últimas ediciones.

videosTitle:
  en: Videos
  es: Vídeos
photosTitle:
  en: Gallery
  es: Galería

videos:
  - title: Crisol de Cuerda 2025 - Making of
    urlId: Tsugsn-L9M8
  - title: Crisol de Cuerda 2024 - Making of
    urlId: FW7xZOcyWco
  - title: Crisol de Cuerda 2023 - Making of
    urlId: SY_SuPfLWFU
  - title: Crisol de Cuerda 2022 - Making of
    urlId: lTXRn6YVzQw
  - title: Crisol de Cuerda 2019 - Making of
    urlId: WZfZ8eTAru8
  - title: Crisol de Cuerda 2018 - Making of
    urlId: QXNVBsOhnqc
  - title: Anatomía Crisol, el documental
    urlId: WC7YX0ngoTY

photosAlbumId: 19SsnPqproGouoSGA
