teachers:
  - id: adam_johannson
    lastInstrument: guitar
    instruments:
      - guitar
    media:
      # bandcamp:
      # fb:
      # instagram:
      # soundcloud:
      # spotify:
      # tiktok:
      # twitter:
      # website:
      # youtubeChannel:
      # youtubeVideo:
    name: Adam Johannson
    years:
      - 2019
      - 2022

  - id: alasdair_fraser
    lastInstrument: fiddle
    instruments:
      - fiddle
    media:
      # bandcamp:
      fb: https://www.facebook.com/profile.php?id=100063504522623
      instagram: https://www.instagram.com/drivenbow
      soundcloud: https://soundcloud.com/alasdair-fraser-official
      spotify: 1SEfFbNsLpiSaaSfnEObpj
      # tiktok:
      # twitter:
      website: https://alasdairfraser.com
      youtubeChannel: https://www.youtube.com/channel/UCadEjme5oZuy7-tbEsVXImg
      # youtubeVideo:
    name: Alasdair Fraser
    years:
      - 2008
      - 2009
      - 2010
      - 2011
      - 2012
      - 2013
      - 2014
      - 2015
      - 2016
      - 2017
      - 2018
      - 2019
      - 2022
      - 2023
      - 2024
      - 2025

  - id: alberto_ablanedo
    lastInstrument: bouzouki
    instruments:
      - bouzouki
    media:
      # bandcamp:
      # fb:
      # instagram:
      # soundcloud:
      # spotify:
      # tiktok:
      twitter: https://twitter.com/folkenlared
      # website:
      youtubeChannel: https://www.youtube.com/@AlbertoAblanedo
      # youtubeVideo:
    name: Alberto Ablanedo
    years:
      - 2022

  - id: alec_brown
    lastInstrument: cello
    instruments:
      - cello
    media:
      # bandcamp:
      # fb:
      instagram: https://www.instagram.com/alecbrownmusic
      # soundcloud:
      spotify: 6WhBlm6n1SD7qhNUZc3uEC
      # tiktok:
      twitter: https://twitter.com/alecbrownmusic
      # website:
      # youtubeChannel:
      # youtubeVideo:
    name: Alec Brown
    years:
      - 2023

  - id: ana_rossi
    lastInstrument: voice
    instruments:
      - voice
    media:
      bandcamp: https://anarossi.bandcamp.com
      # fb:
      instagram: https://www.instagram.com/anarossiarias/
      # soundcloud:
      spotify: 5YiYxfGOBBuY3L5x69dbRQ
      # tiktok:
      # twitter:
      website: https://anarossi.es/
      youtubeChannel: https://www.youtube.com/channel/UCCoCAnAsCVf-4kLPrViXtPg
      # youtubeVideo:
    name: Ana Rossi
    years:
      - 2015
      - 2016
      - 2017
      - 2018
      - 2019
      - 2022
      - 2023

  - id: anders_hall
    lastInstrument: fiddle
    instruments:
      - fiddle
    media:
      # bandcamp:
      # fb:
      instagram: https://www.instagram.com/hallfiddle
      # soundcloud:
      spotify: 0mCL7mlDB7zRLL13b0fM3q
      # tiktok:
      # twitter:
      website: https://www.thenordicfiddlersbloc.com/
      # youtubeChannel:
      # youtubeVideo:
    name: Anders Hall
    years:
      - 2018
      - 2019

  - id: aoife_granville
    lastInstrument: flute
    instruments:
      - flute
    media:
      # bandcamp:
      fb: http://www.facebook.com/aoife.granville3
      instagram: http://www.instagram.com/aoifegranville5
      # soundcloud:
      spotify: 0spvAdgEvBuoMAXQ221orj
      # tiktok:
      twitter: http://www.twitter.com/aoifegranville
      # website:
      # youtubeChannel:
      youtubeVideo: IS8A_7sR7c8
    name: Aoife Granville
    years:
      - 2024

  - id: arkaitz_miner
    lastInstrument: fiddle
    instruments:
      - fiddle
    media:
      # bandcamp:
      # fb:
      # instagram:
      # soundcloud:
      spotify: 1zKIA3574JXMBl3bBbV9hU
      # tiktok:
      # twitter:
      # website:
      # youtubeChannel:
      # youtubeVideo:
    name: Arkaitz Miner
    years:
      - 2012
      - 2017

  - id: basile_bremaud
    lastInstrument: fiddle
    instruments:
      - fiddle
    name: Basile Brèmaud
    years:
      - 2015

  - id: begona_riobo
    lastInstrument: fiddle
    instruments:
      - fiddle
    name: Begoña Riobó
    years:
      - 2011
      - 2012
      - 2013
      - 2015
      - 2016
      - 2017
      - 2018

  - id: betlem_burcet
    lastInstrument: dance
    instruments:
      - dance
    media:
      # bandcamp:
      # fb:
      instagram: https://www.instagram.com/betlem11/
      # soundcloud:
      # spotify:
      # tiktok:
      # twitter:
      website: https://www.mediterraniaescola.cat/
      youtubeChannel: https://www.youtube.com/@betlemburcet7318
      youtubeVideo: TSvsERERYec
    name: Betlem Burcet
    years:
      - 2023
      - 2024

  - id: blanca_altable
    lastInstrument: fiddle
    instruments:
      - fiddle
    media:
      spotify: 5p64uab8k3FgK1DL1yD2zB
    name: Blanca Altable
    years:
      - 2013
      - 2014
      - 2015
      - 2016
      - 2017
      - 2018
      - 2022
      - 2023
      - 2024
      - 2025

  - id: casey_driessen
    lastInstrument: fiddle
    instruments:
      - fiddle
    name: Casey Driessen
    years:
      - 2014
      - 2016

  - id: chuchi_cuadrado
    lastInstrument: guitar
    instruments:
      - guitar
    name: Jesús Enrique Cuadrado "Chuchi"
    years:
      - 2013
      - 2014
      - 2015
      - 2016
      - 2017
      - 2018
      - 2019
      - 2023

  - id: clara_rodriguez
    lastInstrument: dance
    instruments:
      - dance
    name: Clara Rodríguez
    years:
      - 2015

  - id: caoimhin_ofearghail
    lastInstrument: guitar
    instruments:
      - guitar
    media:
      bandcamp: https://caoimhnfearghail1.bandcamp.com/album/flute-fiddle
      # fb:
      instagram: https://www.instagram.com/caoimhinofearghail
      # soundcloud:
      # spotify:
      # tiktok:
      # twitter:
      website: https://www.caoimhinofearghail.ie/
      youtubeChannel: https://www.youtube.com/@caoimhinofearghail1317
      # youtubeVideo:
    name: Caoimhín Ó Fearghail
    years:
      - 2024

  - id: colin_cotter
    lastInstrument: guitar
    instruments:
      - guitar
    name: Colin Cotter
    years:
      - 2016

  - id: david_aznar
    lastInstrument: accordion
    instruments:
      - accordion
    name: David Aznar
    years:
      - 2015
      - 2016
      - 2017

  - id: diego_galaz
    lastInstrument: fiddle
    instruments:
      - fiddle
    name: Diego Galaz
    years:
      - 2009
      - 2010
      - 2011
      - 2017

  - id: ernesto_briceno
    lastInstrument: fiddle
    instruments:
      - fiddle
    name: Ernesto Briceño
    years:
      - 2016
      - 2018

  - id: francesc_tomas
    lastInstrument: fiddle
    instruments:
      - fiddle
    name: Francesc Tomás "Panxito"
    years:
      - 2019
      - 2022

  - id: galen_fraser
    lastInstrument: fiddle
    instruments:
      - fiddle
    name: Galen Fraser
    years:
      - 2019
      - 2022
      - 2023
      - 2025
      - 2026

  - id: gerry_oconnor
    lastInstrument: fiddle
    instruments:
      - fiddle
    media:
      # bandcamp:
      fb: https://www.facebook.com/GerryOConnorFiddle
      # instagram:
      # soundcloud:
      spotify: 0NHsynkxhVhz1cBuAAteN0
      # tiktok:
      # twitter:
      website: https://www.gerryoconnor.net
      # youtubeChannel:
      youtubeVideo: w492gyDGGs8
    name: Gerry O'Connor
    years:
      - 2024

  - id: hanneke_cassel
    lastInstrument: fiddle
    instruments:
      - fiddle
    name: Hanneke Cassel
    years:
      - 2015

  - id: hugo_franco
    lastInstrument: guitar
    instruments:
      - guitar
    media:
      # bandcamp:
      # fb:
      instagram: https://www.instagram.com/musgofranco/
      # soundcloud:
      spotify: 4DI3XKcHGBdMYQDuafnst5
      # tiktok:
      # twitter:
      # website:
      youtubeChannel: https://www.youtube.com/@hummofranco
      youtubeVideo: RXuj2QSITt8
    name: Hugo Franco
    years:
      - 2025
      - 2026

  - id: ines_sanchez
    lastInstrument: dance
    instruments:
      - dance
    media:
      # bandcamp:
      # fb:
      instagram: https://www.instagram.com/ines.saltamontes
      # soundcloud:
      # spotify:
      # tiktok:
      # twitter:
      # website:
      # youtubeChannel:
      # youtubeVideo:
    name: Inés Sánchez
    years:
      - 2025

  - id: jaime_munoz
    lastInstrument: flute
    instruments:
      - flute
    name: Jaime Muñoz
    years:
      - 2010
      - 2011
      - 2012
      - 2017
      - 2018

  - id: jeanmichel_veillon
    lastInstrument: flute
    instruments:
      - flute
    name: Jean-Michel Veillon
    years:
      - 2022

  - id: john_mcintyre
    lastInstrument: guitar
    instruments:
      - guitar
    name: John McIntyre
    years:
      - 2023

  - id: jose_climent
    lastInstrument: fiddle
    instruments:
      - fiddle
    name: José Climent
    years:
      - 2023

  - id: jose_rocha
    lastInstrument: cello
    instruments:
      - cello
    name: José Ramón Rocha
    years:
      - 2016
      - 2017

  - id: juan_arriola
    lastInstrument: fiddle
    instruments:
      - fiddle
    name: Juan Arriola
    years:
      - 2008
      - 2009
      - 2010
      - 2011
      - 2012
      - 2013

  - id: lena_jonsson
    lastInstrument: fiddle
    instruments:
      - fiddle
    name: Lena Jonsson
    years:
      - 2022

  - id: lisardo_prieto
    lastInstrument: fiddle
    instruments:
      - fiddle
    name: Lisardo Prieto
    years:
      - 2024
      - 2025

  - id: louise_mulcahy
    lastInstrument: flute
    instruments:
      - flute
    name: Louise Mulcahy
    years:
      - 2023

  - id: lucia_lopez
    lastInstrument: dance
    instruments:
      - dance
    media:
      # bandcamp:
      # fb:
      instagram: https://www.instagram.com/lucialopezenrique
      # soundcloud:
      # spotify:
      # tiktok:
      # twitter:
      # website:
      # youtubeChannel:
      # youtubeVideo:
    name: Lucía López
    years:
      - 2025
      - 2026

  - id: luis_nicolas_carrete
    lastInstrument: guitar
    instruments:
      - guitar
    name: Luis Nicolás Carrete
    years:
      - 2024
      - 2025

  - id: maria_san_miguel
    lastInstrument: fiddle
    instruments:
      - fiddle
    name: María San Miguel
    years:
      - 2019
      - 2022
      - 2023

  - id: maria_sanchez
    lastInstrument: dance
    instruments:
      - dance
    name: María Sánchez
    years:
      - 2016
      - 2017
      - 2018

  - id: marta_roma
    lastInstrument: cello
    instruments:
      - cello
    name: Marta Roma
    years:
      - 2017
      - 2019
      - 2022

  - id: marti_hosta
    lastInstrument: percussion
    instruments:
      - percussion
    name: Martí Hosta
    years:
      - 2018

  - id: martin_melendez
    lastInstrument: cello
    instruments:
      - cello
    name: Martín Meléndez
    years:
      - 2014
      - 2015
      - 2016

  - id: natalie_haas
    lastInstrument: cello
    instruments:
      - cello
    media:
      # bandcamp:
      fb: http://www.facebook.com/NatalieHaasCello
      # instagram:
      soundcloud: https://soundcloud.com/natalie-haas-1
      spotify: 41sqaarfB2kCWssI6jM10V
      # tiktok:
      # twitter:
      website: https://www.nataliehaas.com/
      youtubeChannel: https://www.youtube.com/channel/UC0LIpFuC1FS6MSHEK4Roz-Q
      youtubeVideo: 7iLlIQ8Bs-Q
    name: Natalie Haas
    years:
      - 2008
      - 2009
      - 2010
      - 2011
      - 2012
      - 2013
      - 2014
      - 2015
      - 2016
      - 2017
      - 2018
      - 2019
      - 2022
      - 2023
      - 2024

  - id: nicolas_quemener
    lastInstrument: guitar
    instruments:
      - guitar
    name: Nicolas Quemener
    years:
      - 2022

  - id: paula_gomez
    lastInstrument: fiddle
    instruments:
      - fiddle
    name: Paula Gómez
    years:
      - 2017
      - 2022
      - 2023

  - id: pepin_munhalen
    lastInstrument: flute
    instruments:
      - flute
    media:
      # bandcamp:
      # fb:
      # instagram:
      # soundcloud:
      spotify: 5YUx4y6iJf3FkVdyxLOc88
      # tiktok:
      # twitter:
      # website:
      # youtubeChannel:
      # youtubeVideo:
    name: Pepín de Muñalen
    years:
      - 2024
      - 2025

  - id: quico_puges
    lastInstrument: cello
    instruments:
      - cello
    name: Quico Pugès Suárez
    years:
      - 2018
      - 2024
      - 2025

  - id: roberto_cubero
    lastInstrument: mandolin
    instruments:
      - mandolin
    name: Roberto Cubero
    years:
      - 2017
      - 2018
      - 2019

  - id: saul_jimenez
    lastInstrument: fiddle
    instruments:
      - fiddle
    name: Saúl Jiménez Montalvo
    years:
      - 2015

  - id: silvia_quesada
    lastInstrument: voice
    instruments:
      - voice
    media:
      # bandcamp:
      fb: https://www.facebook.com/silviaquesadafrancos/
      instagram: https://www.instagram.com/quesada_silvia
      # soundcloud:
      spotify: 5PwlED4GXgnqItHK1v6d0y
      # tiktok:
      twitter: https://twitter.com/silviaquesada
      # website:
      # youtubeChannel:
      # youtubeVideo:
    name: Silvia Quesada
    years:
      - 2024
      - 2025

  - id: suso_cancelas
    lastInstrument: dance
    instruments:
      - dance
    name: Suso Cancelas
    years:
      - 2014
      - 2019
      - 2022

  - id: tatiana_hargreaves
    lastInstrument: fiddle
    instruments:
      - fiddle
    media:
      bandcamp: http://tatianahargreaves.bandcamp.com/
      fb: https://www.facebook.com/tatianahargreaves
      instagram: https://www.instagram.com/dragonfiddler
      spotify: 63Xd2NZV9SzwjChcdH5QsK
      website: https://www.tatianahargreaves.com
      youtubeVideo: 76zNOeTh6Lg
    name: Tatiana Hargreaves
    years:
      - 2025

  - id: toby_kuhn
    lastInstrument: cello
    instruments:
      - cello
    name: Toby Kuhn
    years:
      - 2025
      - 2026
    media:
      instagram: https://www.instagram.com/toby.cello
      spotify: 1BBC6bIXPyvsWkJGCNmWY5
      youtubeChannel: https://www.youtube.com/@tobykuhn441
      youtubeVideo: wpyC8-1Ynvg

  - id: tony_mcmanus
    lastInstrument: guitar
    instruments:
      - guitar
    name: Tony McManus
    years:
      - 2017
      - 2018

  - id: xavi_lozano
    lastInstrument: flute
    instruments:
      - flute
    name: Xavi Lozano
    years:
      - 2018
      - 2019

  - id: xose_liz
    lastInstrument: bouzouki
    instruments:
      - flute
      - guitar
      - bouzouki
    media:
      # bandcamp:
      # fb:
      instagram: https://www.instagram.com/xoseliz/
      soundcloud: https://soundcloud.com/user-497551159
      # spotify:
      # tiktok:
      # twitter:
      # website:
      youtubeChannel: https://www.youtube.com/channel/UC5k5f86Z8NLFKGKYHTMUvFA
      youtubeVideo: giDHRL7tSuQ
    name: Xosé Liz
    years:
      - 2011
      - 2013
      - 2014
      - 2016
      - 2017
      - 2018
      - 2019
      - 2022
      - 2023
      - 2024
      - 2025

  - id: zoe_conway
    lastInstrument: fiddle
    instruments:
      - fiddle
    name: Zoë Conway
    years:
      - 2023
